== Aan de slag

* Kopieer het jAPK template naar een nieuwe pagina.
* Voer de controles uit en vul de uitkomst (groen, oranje of rood) in op die nieuwe pagina.
* Bepaal als laatste pas het eindoordeel:
** Groen: Je hebt voldoende vertrouwen in de applicatie dat je er beheer en onderhoud op kunt uitvoeren.
** Oranje: Veranderingen brengen enig risico met zich mee, maar meestal zijn daar wel oplossingen voor te vinden.
** Rood: Je hebt eigenlijk geen vertrouwen in deze applicatie. Veranderingen hebben een hoog risico, als ze al uitgevoerd kunnen worden.

Het eindoordeel is géén rekenkundige formule. Een applicatie met een paar oranje controles kan nog prima overall groen uitkomen.

Tips::
* Voer, als je de jAPK uitvoert, alléén de controles uit. Los de gevonden problemen niet meteen op.
* Zorg dat de uitkomst voor iedereen zichtbaar is, kwaliteit is een gezamelijk doel.
* Probeer geen issues te verbergen of een schuldige aan te wijzen, kijk wat er nodig is om ze op te lossen.
* De gevonden issues kunnen volgens het normale ontwikkelproces worden ingepland en uitgevoerd.

